[[entries]]
title = "Discography of American Historical Recordings"
description = "As described: \"DAHR currently includes information on more than 31,000 master recordings (matrixes) made by Victor, Columbia, OKeh, Berliner, Edison, Zonophone, Leeds & Catlin, Brunswick, and Decca.\" Indeed, this wide-ranging catalog covers the earliest commerical recordings in the 1890s, the peak decades jazz/swing and regional/ethnic records in the 1920s and 30s, and recordings on the Decca label up through the early 1970s. Notably missing are full discographies from some of the \"race record\" labels like Vocalion and Paramount that recorded Delta blues artists like Charley Patton and Robert Johnson. Recording matrixes are searchable by title, performer, date, label, and other fields. Entries include links to data on other sites and streaming audio where available in the public domain."
author = "UC Santa Barbara Library, Department of Special Collections"
url = "https://adp.library.ucsb.edu/index.php"

[[entries]]
title = "Hank Williams: A Comprehensive Discography"
description = "Attempts to sort out a recording history muddled by undated sessions and overdubbed posthumous releases. Also includes discographies for The Carter Family, Johnny Cash, and Kitty Wells."
author = "Mike Taylor"
url = "https://www.hankwilliamsdiscography.com/index.php"
lastUpdated = "2013"