[[entries]]
title = "Slippery-Hill"
description = "Streaming audio of fiddlers playing old-time tunes from field recordings, festivals, and other non-commercial sources. Includes Appalachian fiddlers and some from other parts of the US and Canada. Recordings are searchable and indexed by title, artist, tuning, key, and collection (with several collections corresponding to published tune books)."
author = "Larry Warren"
url = "https://www.slippery-hill.com/search-page"

[[entries]]
title = "Berea Sound Archives"
description = "As described: \"Berea's non-commercial audio and video collections document Appalachian history and culture, and the history of Berea College. . . . These collections include field recordings from homes and churches, local and regional folk festivals, student performances, presentations of notable scholars, preachers, and social activists who have visited Berea.\""
author = "Berea College (Kentucky)"
url = "https://soundarchives.berea.edu/"
lastUpdate = "2018"

[[entries]]
title = "Samuel Preston Bayard Folklore Recordings"
description = "Field recordings of songs and tunes by old-timers in Southwestern Pennsylvania made between 1948 and 1962."
author = "Penn State University, Special Collections Library"
url = "https://www.youtube.com/playlist?list=PLfkrWr_vIGB9l33oOjTC2M6JlhxfoPlQz"

[[entries]]
title = "The Field Recorders' Collective"
description = "Albums of recorded music by old-time performers, many from Appalachia and Southern states. Available for purchase or to preview as lo-fi streaming audio."
url = "https://fieldrecorder.bandcamp.com/"
