[[entries]]
title = "The Traditional Ballad Index: An Annotated Bibliography of the Folk Songs of the English-Speaking World"
description = "Large index of traditional ballads and folk songs. Entries are organized by song title with cross-references for alternate titles,  variations, and contrafacta. Links are provided to corresponding entries in the Roud Folk Song Index. Print sources and known recordings are listed in abbreviated form, with catalog numbers for recordings. Full citations can be looked up in separate bibliography and discography indexes. Many entries include annotations providing thematic analysis and context for how themes and persons may be linked to historical events. The full database may be downloaded as a zipped text file."
author = "Robert B. Waltz and David G. Engle"
url = "http://www.csufresno.edu/folklore/BalladIndexTOC.html"
lastUpdated = "2020"

[[entries]]
title = "Folk Music Index"
description = "Large searchable index developed by cross-referencing song titles, artists/performers, and composer credits from a database of nearly 5000 audio releases (LPs, CDs, cassettes, and 45-RPM singles) and more than 500 printed sources (books, magazines, sheet music, folios). The database was methodically compiled by a teacher/performer of traditional music who also had a career as a library professional during the first decade of the World Wide Web. Recorded sources were collected beginning in the 1970s, incorporating new compilation releases and recordings by contemporary artists up to 2013."
author = "Jane Keefer"
url = "http://www.ibiblio.org/folkindex/index.htm"
lastUpdated = "2013"

