[[entries]]
title = "Roud Folk Song Index"
description = "The main purpose of the Roud Index is to group together song variants that likely spring from a common source and to assign a unique identifier to each grouping. In this way, the Roud Index can be seen as an extension of Francis James Child's project to construct a comprehensive classification of traditional English-language ballads from extant sources. Whereas Child's life work resulted in 305 numbered ballads, the Roud Index is reported to include 25,000 songs drawn from 18th and 19th century broadsides, popular sheet music and song books, pre-WWII commercial recordings, and the field recordings of folk collectors. English, Scottish, Irish, and American songs (including African-American blues and spirituals) are well represented. The index can be searched from the main page of the Vaughan Williams Memorial Library's website. Most records contain only citations, but some results also link to digitized source materials. The search interface is not the most user-friendly and can sometimes be slow to return results (from a US East Coast location)."
author = "Steve Roud"
url = "https://www.vwml.org/"

[[entries]]
title = "List of Folk Songs by Roud Number"
description = "This Wikipedia page is a crowd-sourced list of songs included in the Roud Folk Song Index. Many song entries include a link to the Wikipedia page for that song."
url = "https://en.wikipedia.org/wiki/List_of_folk_songs_by_Roud_number"

[[entries]]
title = "The Traditional Ballad Index: An Annotated Bibliography of the Folk Songs of the English-Speaking World"
description = "Large index of traditional ballads and folk songs. Entries are organized by song title with cross-references for alternate titles,  variations, and contrafacta. Links are provided to corresponding entries in the Roud Folk Song Index. Print sources and known recordings are listed in abbreviated form, with catalog numbers for recordings. Full citations can be looked up in separate bibliography and discography indexes. Many entries include annotations providing thematic analysis and context for how themes and persons may be linked to historical events. The site is entirely static HTML, which makes it easy to navigate or search by keyword. The full database may also be downloaded as a zipped text file."
author = "Robert B. Waltz and David G. Engle"
url = "http://www.csufresno.edu/folklore/BalladIndexTOC.html"
lastUpdated = "2020"

[[entries]]
title = "Folk Music Index"
description = "Large searchable index developed by cross-referencing song titles, artists/performers, and composer credits from a database of nearly 5000 audio releases (LPs, CDs, cassettes, and 45-RPM singles) and more than 500 printed sources (books, magazines, sheet music, folios). The database was methodically compiled by a teacher/performer of traditional music who also had a career as a library professional during the first decade of the World Wide Web. Recorded sources were collected beginning in the 1970s, incorporating new compilation releases and recordings by contemporary artists up to 2013. Although the site design looks dated, the index is easy to browse or search, and query results load quickly."
author = "Jane Keefer"
url = "http://www.ibiblio.org/folkindex/index.htm"
lastUpdated = "2013"

[[entries]]
title = "The Traditional Tune Archive"
description = ""
author = "Andrew Kuntz"
url = "https://tunearch.org/wiki/TTA"

[[entries]]
