[[entries]]
title = "The Traditional Tune Archive"
description = "Large searchable index and repository growing out of a dedicated amateur's decades-long project to classify and trace the genealogy of fiddle tunes recorded/collected in the British Isles and North America.  The current version is maintained as a Wiki, allowing for collaborative editing, powerful search capabilities, and a familiar interface. This is a one-of-a-kind resource for dance tunes and airs (as contrasted with lyric songs and ballads, which have been systematically catalogued elsewhere). Entries include classification of meter, tonality, and structure, citations of print sources and recordings, alternate titles, geographic distribution, and music transcriptions rendered from ABC notation."
author = "Andrew Kuntz"
url = "https://tunearch.org/wiki/TTA"

[[entries]]
title = "Old Time Fiddle Tunes"
description = "As described: \"Transcriptions and audio files of over 600 traditional fiddle tunes from old recordings, festivals, jams, and workshops.\" A nicely curated selection of tunes reflecting different regional fiddling cultures. Clean, modern website with fast-loading resources."
author = "John Lamancusa"
url = "https://www.mne.psu.edu/lamancusa/tunes.html"

[[entries]]
title = "North Atlantic Tune List"
description = "As described: \"This site is a somewhat random reference source for mostly traditional dance and fiddle tunes from several regions around the North Atlantic: Scandinavia, the British Isles, Quebec, Cape Breton, Métis (Saskatchewan & Manitoba), New England, Appalachia, and more. It is intended as a resource for musicians wanting to learn a tune or remember how particular tunes are played.\" ABC notation is provided for many of the tunes, along with low-resolution images of the sheet music. Tune entries include streaming audio and embedded YouTube videos featuring both amateur and professional performers, including some simplified and slowed-down versions for learning purposes."
url = "https://www.natunelist.net/"

[[entries]]
title = "Australian Traditional Music Tunes Archive"
description = "As described: \"a searchable collection of tunes in ABC Music Notation format . . . and associated supporting bio and documentary material\". Audio files for some of the tunes can be located on another part of the site. Pages load slowly from a US East Coast location, likely because data is being transmitted from a server in Australia."
author = "Ray Mulligan and contributors"
url = "https://bushtraditions.wiki/tunes/index.php/Main_Page"

[[entries]]
title = "Tune Collections on the Internet"
description = "An index of sites with freely available music notation for dance tunes and folk instrumentals from various regions of Europe, North American, and Australia. Identifies which sites have sheet music in image/PDF formats and which have ABC notation. A few of the links may be outdated, but the site is actively maintained as of 2020. This is a great resource for finding obscure or unfamiliar folk material on sites you wouldn't otherwise come across."
author = "Mickey Koth"
url = "https://www.biteyourownelbow.com/webtunes.htm"



