# Web Archives

[[entries]]
title = "Roots of Bluegrass Music: Early Country Music"
description = "Historical and biographical information on pre-WWII recording artists, folk-song collectors, and their informants. Includes extensive bibliographic references. (Unfortunately, individual pages on this site load slowly – the content is rendered by a CMS database application that appears to be poorly optimized.)"
creator = "Richard L. Matteson, Jr."
url = "http://www.bluegrassmessengers.com/roots.aspx"

[[entries]]
title = "Bluegrass Lyrics"
description = "This collection includes lyrics, music notation, and extensive source notes for traditional ballads and fiddle/banjo tunes, as well as popular standards in Bluegrass and related modern genres. Some comparative analysis of songs/tunes/versions is interspersed. (Unfortunately, individual pages on this site load slowly – the content is rendered by a CMS database application that appears to be poorly optimized.)"
creator = "Richard L. Matteson, Jr."
url = "http://www.bluegrassmessengers.com/bluegrass-lyrics.aspx"
