sail-away-ladies = "Sail away ladies"
soldiers-joy = "Soldier’s joy"
st-james-infirmary = "St. James infirmary"
sumer-is-icumen = "Sumer is icumen in"

# The Girl I Left Behind (Me)
# Cumberland Gap
# L'il Liza Jane
# Black Eyed Suzie
# The Cuckoo
# Bonaparte's Retreat
# Old Joe Clark
# Black Jack David
# Molly Put the Kettle On
