# Song
canonicalName = "Sumer is icumen in"
description = "Jubilant 13th-century round composed in Wessex dialect. Notable for early use of polyphonic harmony and Major (Ionian) mode. Slight changes in pronunciation yeild roughly modern English."

[[transcriptions]]
url = "https://www.bl.uk/collection-items/sumer-is-icumen-in"
[transcriptions.publication]
  title = "Collection of poems including fables and musical, calendrical, and medical texts"
  place = "Oxford"
  country = "England"
  year = "abt. 1260"
  catalogRef = "British Library: Harley MS 978"

[[transcriptions]]
pageNumber = "26"
[transcriptions.publication]
  title = "Popular music of the olden time: a collection of ancient songs, ballads, and dance tunes illustrative of the national music of England"
  primaryAuthor = "Chappell"
  credits = [
    "AUTHOR: W. Chappell",
    "ARRANGER (harmonies): G. A. MacFarren",
  ]
  publisher = "Cramer, Beale, and Chappell"
  place = "London"
  country = "England"
  year = "1859"
  vol = "1"
  url = "https://archive.org/details/popularmusicofol01chapuoft"

[[recordings]]
artists = ["The English Singers"]
sessionType = "COMMERCIAL"
place = "East Aurora, NY"
country = "US"
matrixNum = "3443"
[recordings.release]
  year = "1928"
  label = "Roycroft"
  country = "US"
  isSingle = true
  catalogNum = "159"
  url = "https://www.earlymusicamerica.org/web-articles/english-singers-early-recordings-live-again/"
[recordings.streaming]
  archiveId = "78_sumer-is-icumen-in_the-english-singers-john-of-fornsete_gbia0017694b"

[[recordings]]
artists = ["Alfred Deller", "The Deller Consort"]
sessionType = "COMMERCIAL"
[recordings.release]
  title = "Tavern Songs, Vol. 2"
  year = "1961"
  label = "Vanguard"
  country = "US"
  catalogNum = "BG 602"
  discogsId = "7858462"
[recordings.compilation]
  title = "The Art of Alfred Deller"
  year = "1977"
  label = "Vanguard"
  country = "US"
  discogsId = "9488266"
[recordings.streaming]
  spotifyId = "2hJYCwhUqTC4IC7GC5CtTj"
  tidalId = "116579367"
  youtubeId = "O2--oWaO_xE"

[[recordings]]
title = "Summer is icumen in"
artists = ["Elizabeth Mitchell"]
sessionType = "COMMERCIAL"
[recordings.release]
  title = "Blue Clouds"
  year = "2012"
  label = "Smithsonian Folkways"
  country = "US"
  url = "https://folkways.si.edu/elizabeth-mitchell/summer-is-icumen-in/american-folk-childrens/music/track/smithsonian"
[recordings.streaming]
  spotifyId = "6pzMPx471rOF29UozzVuJZ"
  tidalId = "45843022"
  youtubeId = "xzcSsoeQXP8"

[[recordings]]
artists = ["Ocarine Gaggle"]
sessionType = "COMMERCIAL"
[recordings.release]
  title = "Ocarine in Concerto"
  year = "2015"
[recordings.streaming]
  spotifyId = "0NAIVXzG6P0rxGwYxhedpD"
  tidalId = "47372416"
  youtubeId = "mCR9fPUGkSw"

[[arrangements]]
format = "vextab"
instruments = "4-string (DADA)"
tonic = "D"
mode = "ion"
content = """
  options stave-distance=25 font-size=11
  
  tabstave
    notation=true key=D time=6/8
    strings=4 tuning=A/4,D/4,A/3,D/3
  voice
    notes :q 5/1 :8 4/1 :q 2/1 :8 4/1 $Sum-,mer,is,a$ |
    notes :q 5/1 :8 5/1 $com-,ing$ 4p2p0/1 ^3^ $in, , $ 
  voice
    notes :hd (0/4.0/3.0/2) | :hd ##

  options space=25
  tabstave
    notation=true key=D
    strings=4 tuning=A/4,D/4,A/3,D/3
  voice
    notes :q 4/2 :8 4/2 :q 5/2 :8 2/2 $Loud-,ly,sing,Cuc-$ |
    notes :h 4/2 :q ## $koo, $
  voice
    notes :hd (0/3) | :hd (0/4.0/3)
  
  options space=25
  tabstave
    notation=true key=D
    strings=4 tuning=A/4,D/4,A/3,D/3
  voice
    notes :q 0/2 :8 4/2 :q 2/2 :8 5/2 $Grow-,eth,seed,and$ |
    notes :q 4/2 :8 4/2 :q 2/2 :8 0/2 $blow-,eth,mead,and$
  
  options space=25
  tabstave
    notation=true key=D
    strings=4 tuning=A/4,D/4,A/3,D/3
  voice
    notes :q 4/2 :8 0/1 :q 2/1 :8 2/1 $spring,the,wood,a-$ |
    notes :hd 0/1 $new$
  voice
    notes :hd 0/3 | :hd (0/4.0/3.0/2)
  
  options space=25
  tabstave
    notation=true key=D
    strings=4 tuning=A/4,D/4,A/3,D/3
  voice
    notes :qd 5-2/1 $Sing,Cuc-$ | :hd 5/1 $koo!$
  voice
    notes :hd (0/3.0/2) | :hd (0/2)
  
  options space=25
  tabstave
    notation=true key=D
    strings=4 tuning=A/4,D/4,A/3,D/3
  voice
    notes :q 0/1 :8 4/2 :q 5/2 :8 2/2 $Ew-,e,bleat-,eth$ |
    notes :q 4/2 :8 0/1 :q 5/2 :8 4/2 $af-,ter,lamb,and$

  options space=25
  tabstave
    notation=true key=D
    strings=4 tuning=A/4,D/4,A/3,D/3
  voice
    notes :q 0/2 :8 4/2 :q 2/2 :8 4/3 $af-,ter,calf,the$ |
    notes :hd 0/2 $cow$
  voice
    notes :hd 0/3 | :hd (0/3)
    
  options space=25
  tabstave
    notation=true key=D
    strings=4 tuning=A/4,D/4,A/3,D/3
  voice
    notes :q 4/2 :8 4/2 :q 5/2 :8 2/2 $Bull-,ock,stert-,eth$ |
    notes :q 0/1 :8 0/1 :q 2/1 :8 4/1 $Buck-,e,vert-,eth$
    
  options space=25
  tabstave
    notation=true key=D
    strings=4 tuning=A/4,D/4,A/3,D/3
  voice
    notes :q 5/1 :8 4/1 :q 2/1 :8 4/1 $Mer-,ry,sing,Cuc-$ |
    notes :hd 5/1 $koo!$
  voice
    notes :hd (0/3.0/2) | :hd (0/2)
    
  options space=25
  tabstave
    notation=true key=D
    strings=4 tuning=A/4,D/4,A/3,D/3
  voice
    notes :qd 0-2/1 $Cuc-,koo-$ |
    notes :qd 0/1 :q 5/2 :8 p4/2 $koo!, , $
  voice
    notes :hd (0/3.0/2) | :hd (0/2)
    
  options space=25
  tabstave
    notation=true key=D
    strings=4 tuning=A/4,D/4,A/3,D/3
  voice
    notes :q 0/2 :8 4/2 :q 5/2 :8 2/2 $Well,sing'st,thou,cuc-$ |
    notes :qd 4/2 :q s5/2 :8 0/1 $koo!, ,Nor$
  voice
    notes :hd 0/3 | :hd (0/4.0/3)
  
  options space=25
  tabstave
    notation=true key=D
    strings=4 tuning=A/4,D/4,A/3,D/3
  voice
    notes :q 4/2 :8 0/1 :q 2/2 :8 4/3 $cease,thou,e-,ver$ |
    notes :hd 0/2 $now.$
  voice
    notes :hd 0/3 | :hd (0/4.0/3)

"""
source = "MELODY/LYRICS: Chappell (1859), LYRICS: Mitchell (2012)"
