# Publication

displayAuthor = "Brown"
year = "1782"
title = "The goldfinch, or new modern songster: being a select collection of the most admired and favourite Scots and English songs, cantatas, &c."
credits = []
publisher = "Printed for A. Brown"
place = "Edinburgh"
country = "Scotland"
url = "https://archive.org/details/goldfinchornewmo01rugg"
