# Publication

displayAuthor = "Burke, Boykin & Co."
year = "1863"
title = "The Dixieland songster"
credits = []
publisher = "Burke, Boykin & Co."
place = "Macon, GA"
country = "United States"
url = "https://archive.org/details/dixielandsongste01maco"
