# Publication

displayAuthor = "De Witt"
year = "1860"
title = "Patriotic Songster"
credits = []
publisher = "Robert M. De Witt"
place = "New York"
country = "United States"
url = "https://archive.org/details/patrioticsongste00dewi"
