# Publication

displayAuthor = "Dick & Fitzgerald"
year = "1863"
title = "The Arkansas Traveller's songster: containing the celebrated story of the Arkansas traveller with the music for violin or piano, and also, an extensive and choice collection of new and popular comic and sentimental songs"
credits = []
publisher = "Dick & Fitzgerald"
place = "New York"
country = "United States"
url = "https://archive.org/details/arkansastravelle00newy"
