# Publication

displayAuthor = "Dick & Fitzgerald"
year = "1864"
title = "The universal book of songs and singer's companion: containing an extensive collection of patriotic, sentimental, Irish, Ethiopian, comic and jolly convivial songs, embracing all the most popular vocal gems extant"
credits = []
publisher = "Dick & Fitzgerald"
place = "New York"
country = "United States"
url = "https://archive.org/details/universalbookofs00moor"
