# Publication

displayAuthor = "Harrison & Co."
year = "1784"
title = "The vocal magazine; or, compleat British songster: consisting of such English, Scotch, and Irish songs, catches, glees, cantatas, airs, ballads, &c. as are deemed most worthy of being transmitted to posterity"
credits = []
publisher = "Printed for Harrison & Co."
place = "London"
country = "England"
url = "https://archive.org/details/vocalmagazineorc00rugg"
