# Publication

displayAuthor = "Jones & Co."
year = "1878"
title = "The universal songster, or, museum of mirth: forming the most complete, extensive, and valuable collection of ancient and modern songs in the English language"
vol = "3"
credits = []
publisher = "Jones & Co."
place = "London"
country = "England"
url = "https://archive.org/details/universalsongste03crui"
