# Publication

displayAuthor = "Merriam"
year = "1800"
title = "The echo; or, Columbian songster: being a large collection of the most celebrated, modern poetical writings, of different authors"
credits = []
publisher = "E. Merriam"
place = "Brookfield, MA"
country = "United States"
edition = "2"
url = "https://archive.org/details/echoorcolumbians00merr"
