# Publication

displayAuthor = "Miller"
year = "1805"
title = "The Caledonian songster: a selection of choice Scottish songs"
credits = []
publisher = "T. Oliver for George Miller"
place = "Edinburgh"
country = "Scotland"
url = "https://archive.org/details/caledoniansongst00cale"
