displayAuthor = "Shoemaker"
year = "1919"
title = "Northern Pennsylvania minstrelsy: as sung in the backwoods settlements, hunting cabins and lumber camps in Northern Pennsylvania, 1840–1910"
credits = ["AUTHOR: Henry W. Shoemaker"]
publisher = "Altoona Tribune Company"
place = "Altoona, PA"
country = "United States"
url = "https://archive.org/details/northpennsylvani00unse"
